# application-dev.yml (서버 개발 설정)
# 개발 서버 환경 설정
spring:
  data:
  # PostgreSQL 설정
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DEV_DB_HOST}:${DEV_DB_PORT:5432}/${DEV_DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&useUniCode=yes&characterEncoding=UTF-8
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
  # JPA 설정 추가
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

# 쿠키 설정
cookie:
  secure: false
  site: "Strict"

# 개발 환경 로깅 설정
logging:
  config: classpath:log4j2-dev.xml
  level:
    root: INFO
    com.rabbit: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: DEBUG
    com.zaxxer.hikari.pool: INFO
    sun.rmi: WARN
    jdbc.sql-only: DEBUG
    jdbc.sql-timing: DEBUG
    jdbc.result-settable: INFO

app:
  domain: ${DEV_BACKEND_URL}
  frontend-url: ${DEV_FRONTEND_URL}
  invitation:
    expiry-hours: 48  # 초대장 유효 시간 (시간)