spring:
  application:
    name: stt-server
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  config:
    import: optional:file:.env[.properties]

# # Whisper 설정
# whisper:
#   executable:
#     path: ${WHISPER_EXECUTABLE_PATH}
#   model:
#     path: ${WHISPER_MODEL_PATH}
#   working:
#     dir: ${WHISPER_WORKING_DIR}

# Swagger 설정
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: com.firzzle.stt.controller

# Jasypt
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
  secret-key: ${JASYPT_SECRET_KEY}

# Eureka
eureka:
 client:
   register-with-eureka: true
   fetch-registry: true
   service-url:
     defaultZone: ENC(cJOm7bGDAdx9BFBu49TKVNLq8Q0GWOvujo09v6uWSzrDGUy7LpDWE+HoHkCohaFj+4QXgHGgLatmhJJfG4bDSQ==)
 instance:
   instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# MyBatis
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.firzzle.stt.dto,com.firzzle.common.library
  configuration:
    map-underscore-to-camel-case: true
  type-aliases:
    - alias: DataBox
      type: com.firzzle.common.library.DataBox
    - alias: RequestBox
      type: com.firzzle.common.library.RequestBox

# P6Spy
decorator:
  datasource:
    p6spy:
      enable-logging: true

logging:
  config: classpath:logback/logback-local.xml

external:
  api:
    url: ENC(q9n58yBVTV0QE0ZNNxrbiNKX24FlOF70bYww3Z4Q5WGblZv9tGcJzhq5rW7TUowBfruGhsH6HZypaDjV6zNr/g==)
    key: ENC(NvfpCyz8FQxDsP3jIHJ442NqU0IA29d3TAYYdwW0o5G0JuEniYlbbIlm8UjB4fnj)

---
# local 환경
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    jdbc-url: ENC(+lTxE7Jf6xDUX4EbEmIGZdpIvhpuvh7Onxzom7ocQk7tnaWh7HUUHJKv8D7FJaCodQ16ht90bAOBqaOKYqO0moYTUkmiPN/eDaY+IOXcikOD6KrDjT5g/p42qqSPYx3H45TiqQ4Y7VyU/GAqDElydTq34ZBfLNIqzyM3VnoCSiMng77175W9islbKP6My29Mz+OQjs28f/BSa+xvzjuyng==)
    username: ENC(4F57/zxTR7+cKbKWB9GOfD5lSWPM66+bnkDcIN44FYI=)
    password: ENC(gvdMztDAGBXU3MgJPamk6hN4VU0kIzf7fkKvqEflgkA=)
    maximum-pool-size: 10
  kafka:
    listener:
      auto-startup: false
    bootstrap-servers: ENC(XJ6DY46VjPc79rxdBRrA0QjyyzBVYQdeBtagp1pE8hlwUEBAqicJj7J6iiKJe8so)
    consumer:
      group-id: stt-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# 파일 저장 경로
app:
  file-storage:
    upload-dir: C:\SSAFY\uploads
  kafka:
    topic:
      content-analysis: content-analysis-topic

server:
  port: 8080

decorator:
  datasource:
    p6spy:
      enable-logging: false

logging:
  config: classpath:logback/logback-local.xml

---

# dev 환경
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: ENC(tgaaLhoeKpaFq+gSRoyULKnpPwE85+r4rofzbTQRCUf6/+fiw3oQsl/xLNO1MnK+iBHKq1dGPR2IREaL+pDutBV84otxN7oVzh1bM8Z/lVqhr9b0mUV4WjChLf0JlDQ3XU/SHV7vOxpx9aMbp8ihFL9j1YSGM//w22GToW0lADlvS3o3WVSeje0fEB8FppsxF5Wi6762vx7PbTFLmo1OXRoFMa9d8utbitAL1l92WSI=)
    username: ENC(W0ssI5QXuEkllv3MHnpW5SQ7zkbUoHs+2xX9DngxXJI=)
    password: ENC(W0ssI5QXuEkllv3MHnpW5SQ7zkbUoHs+2xX9DngxXJI=)
    maximum-pool-size: 10
  kafka:
    bootstrap-servers: ENC(AuzpvRjsfNfXV5Re6NFHzTYnHPJYaRToi9aEpi4mjZg=)
    consumer:
      group-id: stt-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# 파일 저장 경로
app:
  file-storage:
    upload-dir: /data/firzzle/uploads
  kafka:
    topic:
      content-analysis: content-analysis-topic

server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ENC(spKgsrOQzjPYIfzNCX3o9c+mzyWel4+5R1g8oUDOHSzeruJ0KI6i1yueMvxoYYomaFswLccx4QM596V7LROVHg==)
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

decorator:
  datasource:
    p6spy:
      enable-logging: false

logging:
  config: classpath:logback/logback-dev.xml

---

# production 환경
spring:
  config:
    activate:
      on-profile: production
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: ENC(tgaaLhoeKpaFq+gSRoyULKnpPwE85+r4rofzbTQRCUf6/+fiw3oQsl/xLNO1MnK+iBHKq1dGPR2IREaL+pDutBV84otxN7oVzh1bM8Z/lVqhr9b0mUV4WjChLf0JlDQ3XU/SHV7vOxpx9aMbp8ihFL9j1YSGM//w22GToW0lADlvS3o3WVSeje0fEB8FppsxF5Wi6762vx7PbTFLmo1OXRoFMa9d8utbitAL1l92WSI=)
    username: ENC(W0ssI5QXuEkllv3MHnpW5SQ7zkbUoHs+2xX9DngxXJI=)
    password: ENC(W0ssI5QXuEkllv3MHnpW5SQ7zkbUoHs+2xX9DngxXJI=)
    maximum-pool-size: 20
  kafka:
    bootstrap-servers: ENC(XJ6DY46VjPc79rxdBRrA0QjyyzBVYQdeBtagp1pE8hlwUEBAqicJj7J6iiKJe8so)
    consumer:
      group-id: stt-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# 파일 저장 경로
app:
  file-storage:
    upload-dir: /data/firzzle/uploads
  kafka:
    topic:
      content-analysis: content-analysis-topic

server:
  port: 8080

decorator:
  datasource:
    p6spy:
      enable-logging: false

logging:
  config: classpath:logback/logback-production.xml

