server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: auth-service-v1
          uri: lb://auth-server
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - RewritePath=/api/v1/auth/(?<segment>.*), /v1/${segment}

        - id: auth-service-v2
          uri: lb://auth-server
          predicates:
            - Path=/api/v2/auth/**
          filters:
            - RewritePath=/api/v2/auth/(?<segment>.*), /v2/${segment}

        - id: learning-service-v1
          uri: lb://learning-server
          predicates:
            - Path=/api/v1/learning/**
          filters:
            - RewritePath=/api/v1/learning/(?<segment>.*), /v1/${segment}

        - id: learning-service-v2
          uri: lb://learning-server
          predicates:
            - Path=/api/v2/learning/**
          filters:
            - RewritePath=/api/v2/learning/(?<segment>.*), /v2/${segment}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      #      defaultZone: http://eureka-server:8761/eureka/