server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: auth-route
          uri: lb://auth-server
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>/.*)?, /${segment}

        - id: learning-route
          uri: lb://learning-server
          predicates:
            - Path=/api/learning/**
          filters:
            - RewritePath=/api/*/learning/(?<segment>/.*)?, /${segment}




eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
#      defaultZone: http://eureka-server:8761/eureka/